
services:
  - type: web
    name: private-messenger
    env: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: messenger-db
          type: postgresql
